version: "3.7"
services:
  myapp:
    container_name: django_app
    image: django_app
    build: 
      context: myapp
    ports:
      - "8080:8080"
    networks:
      - net
  proxy:
    container_name: nginx_proxy
    image: nginx_proxy
    build:
      context: proxy
    ports:
      - "80:80"
    networks:
      - net
networks:
  net:

